name: Post welcome comment

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a welcome comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-body: |
            Welcome to the project! Your contribution is greatly appreciated!
